project_id = "pwgjbvtvmjbvfdrxgaob"

[functions.woocommerce-products]
verify_jwt = false

[functions.woocommerce-categories]
verify_jwt = false

[functions.woocommerce-reviews]
verify_jwt = false

[functions.woocommerce-variation-gallery]
verify_jwt = false

[functions.interakt-send-review]
verify_jwt = false

[functions.interakt-tracking-update]
verify_jwt = false

[functions.interakt-account-creation]
verify_jwt = false

[functions.interakt-send-otp]
verify_jwt = false

[functions.interakt-verify-otp]
verify_jwt = false
